**1 / Answer with the type of stats test you would use (assume normal distribution):**
     
       a /  Do students get better test grades if they have a rubber duck on their desk ?  
        T-Test or Mann-Whitney Test, 1-tailed.   
        
       b /  Does smoking affect when or not someone has lung cancer ?  
        Chi-squared.  
        
       c /  Is gender independent of a person’s blood type ?
        Chi-squared  (or, ANOVA ?).
        
       d /  A farming company wants to know if a new fertilizer has improved crop yield or not.  
        T-Test or Mann-Whitney Test, 1-tailed.
        
       e / Does the length of time of the lecture correlate with a student's grade ?
        Pearson's R or Spearman's R.
        
       f/ Do people with dogs live in apartments more than people with cats ?
        Chi-squared.

**2 / Use the following contingency table to help answer the question of whether using a Macbook and being a Codeup student are independent of each other.**


                    Codeup Student 	Not Codeup Student
            Uses a Macbook 	49      20
     Doesn't Use A Macbook 	1       30
     
Based on the above contingency table, it would appear that there is a strong correlation between being a Codeup student and using a Macbook, particularly as compared with those falling under 'Not Codeup Student', hence they are NOT independent.

.




**3 / Choose another 2 categorical variables from the mpg dataset and perform a 𝑐ℎ𝑖2 contingency table test with them. Be sure to state your null and alternative hypotheses.**

In [2]:
# imports

import pandas as pd
from scipy import stats
from pydataset import data
import numpy as np
import env

mpg = data('mpg')
mpg.head()

manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class
1         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
2         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
3         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
4         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact
5         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p  compact

**Hypotheses :**  
    - $H_0$ : Manufacturer is independent of vehicle transmission.  
    -    $H_a$ : Manufacturer is NOT independent of vehicle transmission.

In [11]:
print(mpg['manufacturer'].value_counts())
print('.-.-.-.-')
print(mpg['trans'].value_counts())

dodge         37
toyota        34
volkswagen    27
ford          25
chevrolet     19
audi          18
hyundai       14
subaru        14
nissan        13
honda          9
jeep           8
pontiac        5
land rover     4
mercury        4
lincoln        3
Name: manufacturer, dtype: int64
.-.-.-.-
auto(l4)      83
manual(m5)    58
auto(l5)      39
manual(m6)    19
auto(s6)      16
auto(l6)       6
auto(av)       5
auto(s5)       3
auto(s4)       3
auto(l3)       2
Name: trans, dtype: int64


In [12]:
# removing final 4 characters from 'trans' so that the transmission type 
# fits into solely automatic or manual categories

mpg['trans'] = mpg['trans'].str[:-4]
mpg['trans'].value_counts()

auto      157
manual     77
Name: trans, dtype: int64

In [14]:
mfg_trans_observed = pd.crosstab(mpg.manufacturer, mpg.trans)
mfg_trans_observed

trans         auto  manual
manufacturer              
audi            11       7
chevrolet       16       3
dodge           30       7
ford            17       8
honda            4       5
hyundai          7       7
jeep             8       0
land rover       4       0
lincoln          3       0
mercury          4       0
nissan           8       5
pontiac          5       0
subaru           7       7
toyota          20      14
volkswagen      13      14

In [15]:
chi2_1, p_1, degf_1, expected_1 = stats.chi2_contingency(mfg_trans_observed)

chi2_1, p_1, degf_1, expected_1

# returns chi2, p-value, degree of freedom and an array : the contingency table of 
# expected values if everything were proportional and there were no relationship 
# between the values 'manufacturer' and 'trans'.

(29.293684393117655,
 0.00953444310358795,
 14,
 array([[12.07692308,  5.92307692],
        [12.74786325,  6.25213675],
        [24.82478632, 12.17521368],
        [16.77350427,  8.22649573],
        [ 6.03846154,  2.96153846],
        [ 9.39316239,  4.60683761],
        [ 5.36752137,  2.63247863],
        [ 2.68376068,  1.31623932],
        [ 2.01282051,  0.98717949],
        [ 2.68376068,  1.31623932],
        [ 8.72222222,  4.27777778],
        [ 3.35470085,  1.64529915],
        [ 9.39316239,  4.60683761],
        [22.81196581, 11.18803419],
        [18.11538462,  8.88461538]]))

In [17]:
α = 0.05

# print 'Observed Values' followed by a new line
print('Observed Values :\n')


# print the values from the 'observed' dataframe
print(mfg_trans_observed.values)


# print --- and then a new line, 'Expected Values', followed by another new line
print('---\nExpected Values :\n')


# print the expected values array
print(expected_1.astype(int))
# this turns the floats into integers, for readability


# print a new line
print('---\n')


# print the chi2 value, formatted to a float with 4 digits. 
print(f'chi^2 = {chi2_1:.4f}') 


# print the p-value, formatted to a float with 4 digits {p:.4f}. 
print(f'p     = {p_1:.4f}')

print('---\n')

print(f'Is the p-value < α ?', p_1 < α)

# We know that the expected values are close to the Observed values due to the p-value being greater than α.

Observed Values :

[[11  7]
 [16  3]
 [30  7]
 [17  8]
 [ 4  5]
 [ 7  7]
 [ 8  0]
 [ 4  0]
 [ 3  0]
 [ 4  0]
 [ 8  5]
 [ 5  0]
 [ 7  7]
 [20 14]
 [13 14]]
---
Expected Values :

[[12  5]
 [12  6]
 [24 12]
 [16  8]
 [ 6  2]
 [ 9  4]
 [ 5  2]
 [ 2  1]
 [ 2  0]
 [ 2  1]
 [ 8  4]
 [ 3  1]
 [ 9  4]
 [22 11]
 [18  8]]
---

chi^2 = 29.2937
p     = 0.0095
---

Is the p-value < α ? True


Conclusion :  

    When comparing the two contingency tables, we can see that the observed values are somewhat close to the expected values, due to the p-value being less slightly than α, at p = 0.0095.   
    
    Because the p-value is less than α, _we reject the null hypothesis_, and confirm that, using this available data sample, there DOES appear to be a notable relationship between manufacturer and type of transmission.

**4 / a /  Use the data from the employees database.** Is an employee's gender independent of whether an employee works in sales or marketing?   
(Only look at current employees.) 

In [9]:
db_url = f'mysql+pymysql://{env.username}:{env.password}@{env.host}/employees'
emp_df = pd.read_sql('''SELECT e.gender, e.emp_no, de.dept_no, d.dept_name, de.to_date
                        FROM employees AS e
                        JOIN dept_emp AS de
                            USING (emp_no)
                        JOIN departments as d
                            USING (dept_no)
                        WHERE de.to_date = '9999-01-01' AND d.dept_name IN ('Sales','Marketing')
                        GROUP BY e.gender, e.emp_no, de.dept_no, d.dept_name, de.to_date''', db_url)


SELECT e.gender, e.emp_no, de.dept_no, d.dept_name  
FROM employees AS e  
JOIN dept_emp AS de  
     USING (emp_no)  
JOIN departments as d  
     USING (dept_no)  
WHERE de.to_date = '9999-01-01' AND d.dept_name IN ('Sales','Marketing')
GROUP BY e.gender, e.emp_no, de.dept_no, d.dept_name, de.to_date


In [10]:
emp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52543 entries, 0 to 52542
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   gender     52543 non-null  object
 1   emp_no     52543 non-null  int64 
 2   dept_no    52543 non-null  object
 3   dept_name  52543 non-null  object
 4   to_date    52543 non-null  object
dtypes: int64(1), object(4)
memory usage: 2.0+ MB


In [17]:
α = 0.05
print(emp_df['gender'].value_counts())
print(emp_df['dept_name'].value_counts())


M    31680
F    20863
Name: gender, dtype: int64
Sales        37701
Marketing    14842
Name: dept_name, dtype: int64


**Hypotheses**  
      
    $H_0$ : Employee gender is indepenent of whether an employee works in Sales or in Marketing.    
    $H_a$ : Employee gender is NOT independent of whether an employee works in Sales or in Marketing. 

In [13]:
gend_dept_observed = pd.crosstab(emp_df.gender, emp_df.dept_name)
gend_dept_observed


dept_name  Marketing  Sales
gender                     
F               5864  14999
M               8978  22702

In [18]:
chi2_2, p_2, degf_2, expected_2 = stats.chi2_contingency(gend_dept_observed)

chi2_2, p_2, degf_2, expected_2


# Returns chi2, p-value, degree of freedom and an array : 
# The contingency table of expected values if everything were 
# proportional and there were no relationship between 
# the values 'gender' and 'dept_name'.

(0.3240332004060638,
 0.5691938610810126,
 1,
 array([[ 5893.2426013, 14969.7573987],
        [ 8948.7573987, 22731.2426013]]))

In [28]:

# print 'Observed Values' followed by a new line
print('Observed Values :\n')


# print the values from the 'observed' dataframe
print(gend_dept_observed.values)


# print --- and then a new line, 'Expected Values', followed by another new line
print('---\nExpected Values :\n')


# print the expected values array
print(expected_2.astype(int))
# this turns the floats into integers, for readability


# print a new line
print('---\n')


# print the chi2 value, formatted to a float with 4 digits. 
print(f'chi^2 = {chi2_2:.5f}') 


# print the p-value, formatted to a float with 4 digits {p:.4f}. 
print(f'p     = {p_2:.5f}')

print('---\n')

print(f'Is the p-value < α ?', p_2 < α, ".", "\nIf p > α is True, then the Expected values are close to the Observed values and we fail to reject the null hypothesis.")

# We know that the Expected values are close to the Observed values when the p-value is greater than α.

Observed Values :

[[ 5864 14999]
 [ 8978 22702]]
---
Expected Values :

[[ 5893 14969]
 [ 8948 22731]]
---

chi^2 = 0.32403
p     = 0.56919
---

Is the p-value < α ? False . 
If p > α is True, then the Expected values are close to the Observed values and we fail to reject the null hypothesis.


**Conclusion**

        The Observed values and the Expected values are very similar, having a p-value of 0.56919, as also evidenced by observing the data themselves.
    
        Therefore, we fail to reject the null hypothesis, which stated that gender is independent of working in Sales or in Marketing.

**4 /  b /  Is an employee's gender independent of whether or not they are or have been a manager ?**
      
      


SELECT e.gender, e.emp_no, t.title, t.to_date  
FROM employees AS e  
JOIN titles AS t  
     USING (emp_no)  
WHERE t.to_date = '9999-01-01' AND t.title like '%mana%'  
GROUP BY e.gender, e.emp_no, t.title, t.to_date  

In [34]:
db_url = f'mysql+pymysql://{env.username}:{env.password}@{env.host}/employees'
mgr_df = pd.read_sql('''SELECT e.gender, e.emp_no, t.title, t.to_date
                        FROM employees AS e
                        JOIN titles AS t
                            USING (emp_no)
                        WHERE t.to_date = '9999-01-01' AND t.title IN('Manager')
                        GROUP BY e.gender, e.emp_no, t.title, t.to_date''', db_url)

In [40]:
db_url = f'mysql+pymysql://{env.username}:{env.password}@{env.host}/employees'
not_mgr_df = pd.read_sql('''SELECT e.gender, e.emp_no, t.title, t.to_date
                        FROM employees AS e
                        JOIN titles AS t
                            USING (emp_no)
                        WHERE t.to_date = '9999-01-01' AND t.title NOT LIKE 'manager'
                        GROUP BY e.gender, e.emp_no, t.title, t.to_date''', db_url)

**Hypotheses**  
      
    $H_0$ : Employee gender is independent of whether an employee has been a manager.    
    $H_a$ : Employee gender is NOT independent of whether an employee has been a manager. 

In [36]:
mgr_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   gender   9 non-null      object
 1   emp_no   9 non-null      int64 
 2   title    9 non-null      object
 3   to_date  9 non-null      object
dtypes: int64(1), object(3)
memory usage: 416.0+ bytes


In [59]:
not_mgr_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240115 entries, 0 to 240114
Data columns (total 4 columns):
 #   Column   Non-Null Count   Dtype 
---  ------   --------------   ----- 
 0   gender   240115 non-null  object
 1   emp_no   240115 non-null  int64 
 2   title    240115 non-null  object
 3   to_date  240115 non-null  object
dtypes: int64(1), object(3)
memory usage: 7.3+ MB


In [63]:
print(mgr_df['gender'].value_counts())
print(mgr_df['title'].value_counts())
print(not_mgr_df['title'].value_counts())

M    5
F    4
Name: gender, dtype: int64
Manager    9
Name: title, dtype: int64
Senior Engineer       85939
Senior Staff          82024
Engineer              30983
Staff                 25526
Technique Leader      12055
Assistant Engineer     3588
Name: title, dtype: int64


In [61]:
manager_expected = pd.crosstab(mgr_df.gender, not_mgr_df.title)
manager_expected

title   Engineer  Senior Engineer  Senior Staff  Staff
gender                                                
F              0                2             1      1
M              1                3             1      0

### Q 4, Attempt 2, different strategy

In [45]:
db_url = f'mysql+pymysql://{env.username}:{env.password}@{env.host}/employees'
emp_title_df = pd.read_sql('''SELECT e.gender, e.emp_no, t.title, t.to_date
                        FROM employees AS e
                        JOIN titles AS t
                            USING (emp_no)
                        WHERE t.to_date = '9999-01-01'
                        GROUP BY e.gender, e.emp_no, t.title, t.to_date''', db_url)

In [46]:
emp_title_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240124 entries, 0 to 240123
Data columns (total 4 columns):
 #   Column   Non-Null Count   Dtype 
---  ------   --------------   ----- 
 0   gender   240124 non-null  object
 1   emp_no   240124 non-null  int64 
 2   title    240124 non-null  object
 3   to_date  240124 non-null  object
dtypes: int64(1), object(3)
memory usage: 7.3+ MB


In [67]:
# create a Boolean variable that is a 1 if a employee is a manager (True), or a 0 otherwise (False).

emp_title_df['is_manager'] = (emp_title_df['title'] == 'Manager').astype('int')


In [68]:
# generate a crosstab of managers ('is_manager') and 'gender'
obsv_mgr  = pd.crosstab(emp_title_df['is_manager'], emp_title_df.gender)
 
obsv_mgr 

gender          F       M
is_manager               
0           96006  144109
1               4       5

In [69]:
# run chi-square test
chi2_3, p_3, degf_3, expected_3 = stats.chi2_contingency(obsv_mgr)
chi2_3, p_3, degf_3, expected_3

(0.0,
 1.0,
 1,
 array([[9.60064015e+04, 1.44108599e+05],
        [3.59851577e+00, 5.40148423e+00]]))

In [ ]:
# evaluate results
eval_results(p, α, group1 = '2-seater cars', group2 = '8-cylinder cars')

In [71]:

# print 'Observed Values' followed by a new line
print('Observed Values :\n')


# print the values from the 'observed' dataframe
print(obsv_mgr.values)


# print --- and then a new line, 'Expected Values', followed by another new line
print('---\nExpected Values :\n')


# print the expected values array
print(expected_3.astype(int))
# this turns the floats into integers, for readability


# print a new line
print('---\n')


# print the chi2 value, formatted to a float with 4 digits. 
print(f'chi^2 = {chi2_3:.5f}') 


# print the p-value, formatted to a float with 4 digits {p:.4f}. 
print(f'p     = {p_3:.5f}')

print('---\n')

print(f'Is the p-value < α ?', p_3 < α, ".", "\nIf p < α is False, then the Expected values are close to the Observed values and we fail to reject the null hypothesis.")

# We know that the Expected values are close to the Observed values when the p-value is greater than α.

Observed Values :

[[ 96006 144109]
 [     4      5]]
---
Expected Values :

[[ 96006 144108]
 [     3      5]]
---

chi^2 = 0.00000
p     = 1.00000
---

Is the p-value < α ? False . 
If p < α is False, then the Expected values are close to the Observed values and we fail to reject the null hypothesis.


In [76]:

def eval_results(p_3, α, group1, group2):
    '''
    This function will take in the p-value, alpha and a name for the 2 variables 
    being compared (group 1 and group 2). It will return a string stating whether 
    there exists a relationship between the two groups.
    '''
    if p_3 < α:
        print(f'There exists some relationship between {group1} and {group2}, (p-value: {p_3: .20f}).')
    else:
        print(f'There is not a significant relationship between {group1} and {group2}, (p-value: {p_3: .20f}).')
        

In [78]:
eval_results(p_3, α, group1 = 'gender', group2 = 'title of manager')

There is not a significant relationship between gender and title of manager, (p-value:  1.00000000000000000000).


Conclusion

    The Observed values and the Expected values are very similar, having a p-value of 1.0000, as also evidenced by observing the data themselves.

    Therefore, we fail to reject the null hypothesis, which stated that gender is independent of having a title of manager.