**1 / Answer with the type of stats test you would use (assume normal distribution):**
     
       a /  Do students get better test grades if they have a rubber duck on their desk ?  
        T-Test or Mann-Whitney Test, 1-tailed.   
        
       b /  Does smoking affect when or not someone has lung cancer ?  
        Chi-squared.  
        
       c /  Is gender independent of a person’s blood type ?
        Chi-squared  (or, ANOVA ?).
        
       d /  A farming company wants to know if a new fertilizer has improved crop yield or not.  
        T-Test or Mann-Whitney Test, 1-tailed.
        
       e / Does the length of time of the lecture correlate with a student's grade ?
        Pearson's R or Spearman's R.
        
       f/ Do people with dogs live in apartments more than people with cats ?
        Chi-squared.

**2 / Use the following contingency table to help answer the question of whether using a Macbook and being a Codeup student are independent of each other.**


                    Codeup Student 	Not Codeup Student
            Uses a Macbook 	49      20
     Doesn't Use A Macbook 	1       30
     
Based on the above contingency table, it would appear that there is a strong correlation between being a Codeup student and using a Macbook, particularly as compared with those falling under 'Not Codeup Student', hence they are NOT independent.

.




**3 / Choose another 2 categorical variables from the mpg dataset and perform a 𝑐ℎ𝑖2 contingency table test with them. Be sure to state your null and alternative hypotheses.**

In [21]:
# imports

import pandas as pd
from scipy import stats
from pydataset import data
import numpy as np
import env

mpg = data('mpg')
mpg.head()

manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class
1         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
2         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
3         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
4         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact
5         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p  compact

**Hypotheses :**  
    - $H_0$ : Manufacturer is independent of vehicle transmission.  
    -    $H_a$ : Manufacturer is NOT independent of vehicle transmission.

In [11]:
print(mpg['manufacturer'].value_counts())
print('.-.-.-.-')
print(mpg['trans'].value_counts())

dodge         37
toyota        34
volkswagen    27
ford          25
chevrolet     19
audi          18
hyundai       14
subaru        14
nissan        13
honda          9
jeep           8
pontiac        5
land rover     4
mercury        4
lincoln        3
Name: manufacturer, dtype: int64
.-.-.-.-
auto(l4)      83
manual(m5)    58
auto(l5)      39
manual(m6)    19
auto(s6)      16
auto(l6)       6
auto(av)       5
auto(s5)       3
auto(s4)       3
auto(l3)       2
Name: trans, dtype: int64


In [12]:
# removing final 4 characters from 'trans' so that the transmission type 
# fits into solely automatic or manual categories

mpg['trans'] = mpg['trans'].str[:-4]
mpg['trans'].value_counts()

auto      157
manual     77
Name: trans, dtype: int64

In [14]:
mfg_trans_observed = pd.crosstab(mpg.manufacturer, mpg.trans)
mfg_trans_observed

trans         auto  manual
manufacturer              
audi            11       7
chevrolet       16       3
dodge           30       7
ford            17       8
honda            4       5
hyundai          7       7
jeep             8       0
land rover       4       0
lincoln          3       0
mercury          4       0
nissan           8       5
pontiac          5       0
subaru           7       7
toyota          20      14
volkswagen      13      14

In [15]:
chi2_1, p_1, degf_1, expected_1 = stats.chi2_contingency(mfg_trans_observed)

chi2_1, p_1, degf_1, expected_1

# returns chi2, p-value, degree of freedom and an array : the contingency table of 
# expected values if everything were proportional and there were no relationship 
# between the values 'manufacturer' and 'trans'.

(29.293684393117655,
 0.00953444310358795,
 14,
 array([[12.07692308,  5.92307692],
        [12.74786325,  6.25213675],
        [24.82478632, 12.17521368],
        [16.77350427,  8.22649573],
        [ 6.03846154,  2.96153846],
        [ 9.39316239,  4.60683761],
        [ 5.36752137,  2.63247863],
        [ 2.68376068,  1.31623932],
        [ 2.01282051,  0.98717949],
        [ 2.68376068,  1.31623932],
        [ 8.72222222,  4.27777778],
        [ 3.35470085,  1.64529915],
        [ 9.39316239,  4.60683761],
        [22.81196581, 11.18803419],
        [18.11538462,  8.88461538]]))

In [17]:
α = 0.05

# print 'Observed Values' followed by a new line
print('Observed Values :\n')


# print the values from the 'observed' dataframe
print(mfg_trans_observed.values)


# print --- and then a new line, 'Expected Values', followed by another new line
print('---\nExpected Values :\n')


# print the expected values array
print(expected_1.astype(int))
# this turns the floats into integers, for readability


# print a new line
print('---\n')


# print the chi2 value, formatted to a float with 4 digits. 
print(f'chi^2 = {chi2_1:.4f}') 


# print the p-value, formatted to a float with 4 digits {p:.4f}. 
print(f'p     = {p_1:.4f}')

print('---\n')

print(f'Is the p-value < α ?', p_1 < α)

# We know that the expected values are close to the Observed values due to the p-value being greater than α.

Observed Values :

[[11  7]
 [16  3]
 [30  7]
 [17  8]
 [ 4  5]
 [ 7  7]
 [ 8  0]
 [ 4  0]
 [ 3  0]
 [ 4  0]
 [ 8  5]
 [ 5  0]
 [ 7  7]
 [20 14]
 [13 14]]
---
Expected Values :

[[12  5]
 [12  6]
 [24 12]
 [16  8]
 [ 6  2]
 [ 9  4]
 [ 5  2]
 [ 2  1]
 [ 2  0]
 [ 2  1]
 [ 8  4]
 [ 3  1]
 [ 9  4]
 [22 11]
 [18  8]]
---

chi^2 = 29.2937
p     = 0.0095
---

Is the p-value < α ? True


Conclusion :  

    When comparing the two contingency tables, we can see that the observed values are somewhat close to the expected values, due to the p-value being less slightly than α, at p = 0.0095.   
    
    Because the p-value is less than α, _we reject the null hypothesis_, and confirm that, using this available data sample, there DOES appear to be a notable relationship between manufacturer and type of transmission.

**4 / a /  Use the data from the employees database.** Is an employee's gender independent of whether an employee works in sales or marketing?   
(Only look at current employees.) 

In [27]:
db_url = f'mysql+pymysql://{env.username}:{env.password}@{env.host}/employees'
emp_df = pd.read_sql('''SELECT * FROM employees 
                        JOIN dept_emp USING (emp_no) 
                        WHERE to_date = "9999-01-01"''', db_url)


In [25]:
emp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240124 entries, 0 to 240123
Data columns (total 9 columns):
 #   Column      Non-Null Count   Dtype 
---  ------      --------------   ----- 
 0   emp_no      240124 non-null  int64 
 1   birth_date  240124 non-null  object
 2   first_name  240124 non-null  object
 3   last_name   240124 non-null  object
 4   gender      240124 non-null  object
 5   hire_date   240124 non-null  object
 6   salary      240124 non-null  int64 
 7   from_date   240124 non-null  object
 8   to_date     240124 non-null  object
dtypes: int64(2), object(7)
memory usage: 16.5+ MB


In [26]:
print(emp_df['gender'].value_counts())
print(emp_df['gender'].value_counts())


M    144114
F     96010
Name: gender, dtype: int64


In [ ]:
## Work-in-progress in a SQL notebook. Not yet been able to resolve.

**4 /  b /  Is an employee's gender independent of whether or not they are or have been a manager ?**
      
      
