In [1]:
%matplotlib inline
import numpy as np
import pandas as pd

import viz # curriculum example visualisations

np.random.seed(29)

#### 1 / How likely is it that you roll doubles when rolling two dice?


In [82]:

n_trials = nrows = 1_0000

n_dice = ncols = 2
# represents number of dice rolled

# using random choice to select from provided-below list. Reshape into columns.
rolls = np.random.choice([1,2,3,4,5,6], n_trials * n_dice).reshape(nrows, ncols)
rolls

array([[2, 2],
       [1, 4],
       [4, 3],
       ...,
       [6, 1],
       [5, 5],
       [3, 4]])

In [83]:
chancey = (pd.DataFrame(rolls)
        .apply(lambda row: row[0] == row[1], axis=1)
        .mean())

chancey

# The lambda does : for each row, check if the digit in the 1st index equals the digit in the 2nd index

0.1697

#### 2 / If you flip 8 coins, what is the probability of getting exactly 3 heads?  What is the probability of getting more than 3 heads?


In [44]:
n_trials = nrows = 1500
n_coins = ncols = 8
H = 0
T = 1


In [45]:
flips = np.random.choice([0, 1], n_trials * n_coins).reshape(nrows, ncols)
flips


array([[0, 0, 0, ..., 0, 1, 1],
       [1, 1, 1, ..., 0, 0, 1],
       [0, 1, 0, ..., 1, 1, 1],
       ...,
       [0, 0, 1, ..., 1, 1, 0],
       [1, 1, 1, ..., 1, 0, 1],
       [1, 1, 1, ..., 1, 0, 0]])

In [46]:
# computing the sum of each roll (event)

sums_of_flips = flips.sum(axis = 1)

# return the array of each sum
sums_of_flips

array([3, 4, 5, ..., 4, 5, 4])

In [47]:
three_heads = sums_of_flips == 3
three_heads

array([ True, False, False, ..., False, False, False])

In [52]:
# probability of flipping a head exactly 3 times

prob3H = three_heads.astype(int).mean()
round(prob3H, 4)

0.2133

In [49]:
more_than_3H = sums_of_flips > 3
more_than_3H

array([False,  True,  True, ...,  True,  True,  True])

In [51]:
# probability of flipping a head more than 3 times

prob_more_than_3H = more_than_3H.astype(int).mean()
round(prob_more_than_3H, 4)

0.6567

#### 3 / There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. 
   Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards past  
   which I drive both have data science students on them ?

In [91]:
p_ds_student = 0.25

# two columns : two billboards
nbillboards = ncols = 2


n_simulated_bboards = nrows = 10 ** 5

In [110]:
data = np.random.random((nrows, ncols))
data

array([[0.9745262 , 0.56478516],
       [0.65743771, 0.26454187],
       [0.79672006, 0.38951768],
       ...,
       [0.98351198, 0.0744022 ],
       [0.93504204, 0.16722165],
       [0.04335091, 0.28693399]])

In [111]:
# how many ds billboards occured, using the generated, random value ?

ds_student = data < p_ds_student
ds_student

array([[False, False],
       [False, False],
       [False, False],
       ...,
       [False,  True],
       [False,  True],
       [ True, False]])

In [112]:
# returns the probability of passing billboards with a ds student

data_face = ds_student.astype(int).mean()
data_face

0.250635

In [113]:
data_face.sum()

0.250635

In [114]:
# probability of two billboards with a data science student on each

(ds_student.sum(axis = 1) == 2).mean()

0.06322

####  4 / Codeup students buy, daily, on average, 3 poptart packages, with a standard deviation of 1.5 a day, from the snack vending machine.  
If, on Monday, the machine is restocked with 17 poptart packages, how likely is it that a person will be able to buy some poptarts on Friday afternoon?   

(Remember, if you have the mean and the standard deviation, use the np.random.normal .) You'll need to make a judgement call on how to handle some of your values.

In [122]:
n_poptarts = nrows = 17
# represents no of poptarts on Monday

n_sold = ncols = 3
# represents number of poptarts sold on a given day

# using random choice to select from provided-below list.

# we will need n_trials * n_dice

vending = np.random.normal()

# reshape into rows of 3 columns
vending

-0.3312850592924172